// Shared display labels for metrics + groups (used by the table and the
// comparison overlay). Pure data — safe to import anywhere.

import type { GroupKey, MetricKey } from "./types.ts";

export const METRIC_LABEL: Record<MetricKey, string> = {
  goals: "G",
  assists: "A",
  npg: "npG",
  shots: "Sh",
  sot: "SoT",
  interceptions: "Int",
  tackles_won: "TklW",
  fouled: "Fld",
  crosses: "Crs",
  fouls: "Fls",
  gk_saves: "Sv",
  gk_clean_sheets: "CS",
  gk_save_pct: "Sv%",
  gk_ga: "GA",
  gk_sota: "SoTA",
  gk_pk_saved: "PKsv",
  conv_pct: "Conv%",
  sot_pct: "SoT%",
  g_per_sot: "G/SoT",
  xg: "xG",
  xa: "xA",
  g_minus_xg: "G−xG",
  gk_goals_prevented: "GP",
  key_passes: "KP",
  big_chances_created: "BCC",
  dribbles: "Drb",
  acc_crosses: "aCrs",
  tackles: "Tkl",
  clearances: "Clr",
  blocks: "Blk",
  ball_recovery: "Rec",
  poss_won_att_third: "Win⅓",
  aerial_won: "Aer",
  duels_won_pct: "Duel%",
  errors: "Err",
  pass_pct: "Pass%",
  passes: "Pass",
  long_balls: "LB",
  long_ball_pct: "LB%",
  final_third_passes: "F3P",
};

// Danish "oversættelse" shown as hover tooltips.
export const METRIC_DESC: Record<MetricKey, string> = {
  goals: "Mål",
  assists: "Assists",
  npg: "Mål uden straffespark (non-penalty goals)",
  shots: "Skud",
  sot: "Skud på mål (shots on target)",
  interceptions: "Erobringer / interceptions",
  tackles_won: "Vundne tacklinger",
  fouled: "Frispark vundet (blev lagt ned)",
  crosses: "Indlæg",
  fouls: "Begåede frispark",
  gk_saves: "Redninger",
  gk_clean_sheets: "Clean sheets (kampe uden mål imod)",
  gk_save_pct: "Redningsprocent (højere er bedre)",
  gk_ga: "Mål imod (lavere er bedre)",
  gk_sota: "Skud på mål imod (lavere er bedre)",
  gk_pk_saved: "Reddede straffespark",
  conv_pct: "Konvertering: mål per skud i % (min. 20 skud)",
  sot_pct: "Skud-præcision: skud på mål per skud i % (min. 20 skud)",
  g_per_sot: "Mål per skud på mål (min. 8 SoT)",
  xg: "Expected goals (Sofascore) — forventede mål ud fra chancekvalitet",
  xa: "Expected assists (Sofascore) — forventede assists",
  g_minus_xg: "Mål minus xG: afslutning over/under forventning (min. 20 skud)",
  gk_goals_prevented: "Goals prevented: reddede mål over forventning (post-shot xG − mål imod)",
  key_passes: "Chances created — afleveringer der fører til skud",
  big_chances_created: "Store chancer skabt — oplæg til oplagte målchancer",
  dribbles: "Vellykkede driblinger (Sofascore)",
  acc_crosses: "Præcise indlæg (Sofascore)",
  tackles: "Tacklinger i alt (Sofascore)",
  clearances: "Clearances — bolde ryddet fra farezonen",
  blocks: "Blokerede skud",
  ball_recovery: "Boldgenerobringer — løse bolde vundet",
  poss_won_att_third: "Bold vundet i sidste tredjedel (high press)",
  aerial_won: "Vundne luftdueller",
  duels_won_pct: "Andel vundne dueller i % (højere er bedre)",
  errors: "Fejl der fører til skud imod (lavere er bedre)",
  pass_pct: "Afleveringspræcision i % (højere er bedre)",
  passes: "Antal afleveringer (spilinvolvering)",
  long_balls: "Præcise lange bolde",
  long_ball_pct: "Lange boldes præcision i % (højere er bedre)",
  final_third_passes: "Præcise afleveringer i sidste tredjedel (fremdrift)",
};

// Full, readable names (for the filter picker etc.). Abbreviations live in
// METRIC_LABEL; show them together as "Full name (ABBR)".
export const METRIC_NAME: Record<MetricKey, string> = {
  goals: "Mål",
  assists: "Assists",
  npg: "Mål uden straffe",
  shots: "Skud",
  sot: "Skud på mål",
  interceptions: "Erobringer",
  tackles_won: "Vundne tacklinger",
  fouled: "Frispark vundet",
  crosses: "Indlæg",
  fouls: "Begåede frispark",
  gk_saves: "Redninger",
  gk_clean_sheets: "Clean sheets",
  gk_save_pct: "Redningsprocent",
  gk_ga: "Mål imod",
  gk_sota: "Skud på mål imod",
  gk_pk_saved: "Reddede straffe",
  conv_pct: "Konvertering",
  sot_pct: "Skud-præcision",
  g_per_sot: "Mål per skud på mål",
  xg: "Expected goals",
  xa: "Expected assists",
  g_minus_xg: "Mål minus xG",
  gk_goals_prevented: "Goals prevented",
  key_passes: "Chances created",
  big_chances_created: "Store chancer skabt",
  dribbles: "Vellykkede driblinger",
  acc_crosses: "Præcise indlæg",
  tackles: "Tacklinger",
  clearances: "Clearances",
  blocks: "Blokeringer",
  ball_recovery: "Boldgenerobringer",
  poss_won_att_third: "Erobringer i sidste tredjedel",
  aerial_won: "Vundne luftdueller",
  duels_won_pct: "Vundne dueller %",
  errors: "Fejl → skud",
  pass_pct: "Afleveringspræcision",
  passes: "Afleveringer",
  long_balls: "Præcise lange bolde",
  long_ball_pct: "Lange bolde %",
  final_third_passes: "Afleveringer i sidste tredjedel",
};

export const GROUP_LABEL: Record<GroupKey, string> = {
  offensive: "Offensive",
  expected: "Expected (xG)",
  creation: "Skabelse",
  efficiency: "Efficiency",
  defensive: "Defensive",
  buildup: "Opspil",
  goalkeeping: "Goalkeeping",
};
